Repository hpi-swa-teaching/MarkdownEditor, pull requests merged in 2019-06, with the labels that each got.

#9 refactors tests
  .gitattributes
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testWindowLabel.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testBoldAttributeDelimiterLength.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testCalculateLengthRaisesStreamEndError.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testCut1FromEnd.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testCut1FromStart.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testCut2FromEnd.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testCut2FromStart.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testInitializationLeftFlanking.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testInitializationLeftRightFlanking.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testInitializationRightFlanking.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testItalicAttributeDelimiterLength.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testLength.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testMatchesOpenerNot.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testMaxDelimiterLengthIs2.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testOpenerAndCloserMatchesOpener.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testPosition.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/instance/testStartPosition.st
  packages/MarkdownEditor-Tests.package/MarkdownEmphasisDelimiterTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownHeadingsTest.class/instance/testFurtherIdeas.st
  packages/MarkdownEditor-Tests.package/MarkdownHeadingsTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testAttributizeText.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testCleanEmptiesAttributes.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testCleanEmptiesTokens.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testCloserDelimiterWithoutOpener.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testCutClosingDelimiter.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testCutOpeningDelimiter.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testDelimiterCantCloseItself.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testDelimiterSpansCanNotOverlap.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testDontFindOpenerForCloserIfBothLengthsIndivisibleBy3.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testFindOpenerForCloserIfBothLengthsDivisibleBy3.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testFindOpenerForCloserIfOnlyOneLengthIsDivisibleBy3.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testFindOpenerForEmphasisDelimiter.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testInterpretTokensAsItalics.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testInterpretTokensBold.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testInterpretTokensCutDelimiterClosesTwice.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testInterpretTokensCutsBoldDelimiters.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testInterpretTokensCutsItalicDelimiters.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testInterpretTokensWithoutEmphasis.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testNextTokenIsCharacter.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testNextTokenIsDelimiter.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testNextTokenStreamEndError.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testParseTwoAttributes.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testProcessingTwoDelimitersRemovesDelimitersInbetween.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testProcessingTwoItalicDelimitersCreatesBoldAttribute.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testProcessingTwoItalicDelimitersCreatesItalicAttribute.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/instance/testTokenize.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineParserTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownReadStreamTest.class/instance/testLast.st
  packages/MarkdownEditor-Tests.package/MarkdownReadStreamTest.class/instance/testPeek.st
  packages/MarkdownEditor-Tests.package/MarkdownReadStreamTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownStringTest.class/instance/testInitialization.st
  packages/MarkdownEditor-Tests.package/MarkdownStringTest.class/instance/testStartPosition.st
  packages/MarkdownEditor-Tests.package/MarkdownStringTest.class/methodProperties.json
Labels: Refactor

#13 Adds license to project
  LICENSE.md
Labels: Text

#11 Fixes theme changing bug
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/buildEditorTextMorphWith..st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/buildWith..st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/markdown..st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/markdown.st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/markdownText..st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/markdownText.st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/methodProperties.json
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/properties.json
  packages/MarkdownEditor-Core.package/MarkdownTextStyler.class/instance/reset.st
  packages/MarkdownEditor-Core.package/MarkdownTextStyler.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/README.md
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/expectedFailures.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/setUp.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/tearDown.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/testApplyingThemeDoesNotThrowError.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/testBuildingEditorReturnsWindow.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/testBuildingEditorTextMorphReturnsSpec.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/testMenuOpenCommand.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/testTextPersistence.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/testWindowCreation.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/testWindowLabel.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/properties.json
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testBuildEditorWithReturnsSpec.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testTextPersistence.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/methodProperties.json
Labels: Failure Fix

#20 Editorconfig and Trunk-Testing
  .editorconfig
  .travis.yml
Labels: Tools

#23 Makes InlineTextStyler usable by itself
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/methodProperties.json
  packages/MarkdownEditor-Core.package/MarkdownHeading.class/instance/asText.st
  packages/MarkdownEditor-Core.package/MarkdownHeading.class/instance/attributes.st
  packages/MarkdownEditor-Core.package/MarkdownHeading.class/instance/textAttribute.st
  packages/MarkdownEditor-Core.package/MarkdownHeading.class/methodProperties.json
  packages/MarkdownEditor-Core.package/MarkdownInlineTextStyler.class/instance/privateStyle..st
  packages/MarkdownEditor-Core.package/MarkdownInlineTextStyler.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownInlineTextStylerTest.class/instance/testEmphasisStylingKeepsAttributes.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineTextStylerTest.class/instance/testPreviousAttributesGetRemoved.st
  packages/MarkdownEditor-Tests.package/MarkdownInlineTextStylerTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownMockTextStyler.class/properties.json
Labels: Improvement
