Repository hpi-swa-teaching/MarkdownEditor, pull requests merged in 2019-05, with the labels that each got.

#1 create window
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/README.md
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/class/initialize.st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/class/open.st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/buildEditorWith..st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/buildWith..st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/markdown..st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/instance/markdown.st
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/methodProperties.json
  packages/MarkdownEditor-Core.package/MarkdownEditor.class/properties.json
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/README.md
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/closeMarkdownEditorWindows.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/markdownWindows.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/setUp.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testBuildEditorWithReturnsSpec.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testBuildWithReturnsWindow.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testMenuOpenCommand.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testTextPersistence.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testWindowCreation.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/properties.json
Labels: [T] Feature

#3 Refactor MarkdownEditor tests
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/closeMarkdownEditorWindows.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/markdownWindows.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/setUp.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/tearDown.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testMenuOpenCommand.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testTextPersistence.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testWindowCreation.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/instance/testWindowLabel.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownEditorTests.class/properties.json
Labels: [T] Refactor

#7 Add coverage testing
  .gitattributes
  .smalltalk.ston
  README.md
Labels: Tools
