Repository hpi-swa-teaching/MarkdownEditor, pull requests merged in 2019-07, with the labels that each got.

#29 Unsupport Squeak 5.0
  .travis.yml
  packages/BaselineOfMarkdownEditor.package/BaselineOfMarkdownEditor.class/instance/baseline..st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/instance/expectedFailures.st
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownMockTextStyler.class/properties.json
Labels: Refactor

#30 Fixes colouring of instance and global variables in code blocks
  .smalltalk.ston
  .squot
  packages/BaselineOfMarkdownEditor.package/BaselineOfMarkdownEditor.class/instance/baseline..st
  packages/BaselineOfMarkdownEditor.package/BaselineOfMarkdownEditor.class/methodProperties.json
  packages/MarkdownEditor-Core.package/MarkdownCodeBlock.class/class/shoutParserClass.st
  packages/MarkdownEditor-Core.package/MarkdownCodeBlock.class/instance/initialize.st
  packages/MarkdownEditor-Core.package/MarkdownCodeBlock.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/MarkdownEditorTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/WeakSmalltalkParserTest.class/README.md
  packages/MarkdownEditor-Tests.package/WeakSmalltalkParserTest.class/instance/rangesForSource..st
  packages/MarkdownEditor-Tests.package/WeakSmalltalkParserTest.class/instance/setUp.st
  packages/MarkdownEditor-Tests.package/WeakSmalltalkParserTest.class/instance/testUnkownLowercaseKeywordIsInstanceVariable.st
  packages/MarkdownEditor-Tests.package/WeakSmalltalkParserTest.class/instance/testUnkownUppercaseKeywordIsGlobalVariable.st
  packages/MarkdownEditor-Tests.package/WeakSmalltalkParserTest.class/methodProperties.json
  packages/MarkdownEditor-Tests.package/WeakSmalltalkParserTest.class/properties.json
  packages/MarkdownEditor-Utilities.package/.filetree
  packages/MarkdownEditor-Utilities.package/.squot-contents
  packages/MarkdownEditor-Utilities.package/UnextendableTextFontReference.class/README.md
  packages/MarkdownEditor-Utilities.package/UnextendableTextFontReference.class/instance/mayBeExtended.st
  packages/MarkdownEditor-Utilities.package/UnextendableTextFontReference.class/methodProperties.json
  packages/MarkdownEditor-Utilities.package/UnextendableTextFontReference.class/properties.json
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/README.md
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/instance/initializeInstanceVariables.st
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/instance/parseBinary.st
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/instance/parseKeyword.st
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/instance/parseUnary.st
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/instance/resolve..st
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/methodProperties.json
  packages/MarkdownEditor-Utilities.package/WeakSmalltalkParser.class/properties.json
  packages/MarkdownEditor-Utilities.package/monticello.meta/categories.st
  packages/MarkdownEditor-Utilities.package/monticello.meta/initializers.st
  packages/MarkdownEditor-Utilities.package/properties.json
Labels: Failure Fix

#32 Enhances README with installation guide and info
  README.md
  screenshots/how-to-open.png
  screenshots/window.png
Labels: Discussion, Text

#31 Adds contributing
  CONTRIBUTING.md
Labels: Text
